
###LIST ALIQUOTAS_ITEMS
GET http://localhost:8000/api/aliquotas_items
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

###VER ALIQUOTAS_ITEMS
GET http://localhost:8000/api/aliquotas_items/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

####ADICIONAR ALIQUOTAS_ITEMS
POST http://localhost:8000/api/aliquotas_items
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "nome":"Loren Epsun",
    "aliquota_id":1,
    "descritivo":"Loren Epsun",
    "porcentagem":1.1

}
####MUDAR ALIQUOTAS_ITEMS
POST http://localhost:8000/api/aliquotas_items/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "_method": "PUT",
    "nome":"Loren Epsun",
    "aliquota_id":1,
    "descritivo":"Loren Epsun",
    "porcentagem":1.1

}

####APAGAR ALIQUOTAS_ITEMS
POST http://localhost:8000/api/aliquotas_items/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "_method": "DELETE"
}
