
###LISTAR NEGOCIOS
GET http://localhost:8000/api/business
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2OTA5OTk3ODMsImV4cCI6MTY5MTAwMzM4MywibmJmIjoxNjkwOTk5NzgzLCJqdGkiOiJWQ1IwNjI5YUp6VGo2Rk9YIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Nxbg24G_I6fUWhM6V3Sr14UNpiX2mSoEeFc2GzVLnt8
Content-Type: application/json
Accept: application/json

###VER NEGOCIOS
GET http://localhost:8000/api/business/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2OTA5OTk3ODMsImV4cCI6MTY5MTAwMzM4MywibmJmIjoxNjkwOTk5NzgzLCJqdGkiOiJWQ1IwNjI5YUp6VGo2Rk9YIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Nxbg24G_I6fUWhM6V3Sr14UNpiX2mSoEeFc2GzVLnt8
Content-Type: application/json
Accept: application/json

####ADICIONAR NEGOCIOS
POST http://localhost:8000/api/business
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2OTA5OTk3ODMsImV4cCI6MTY5MTAwMzM4MywibmJmIjoxNjkwOTk5NzgzLCJqdGkiOiJWQ1IwNjI5YUp6VGo2Rk9YIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Nxbg24G_I6fUWhM6V3Sr14UNpiX2mSoEeFc2GzVLnt8
Content-Type: application/json
Accept: application/json

{
    "fantasia": "TNET SISTEMAS",
    "razao": " TNET LTDA",
    "cnpj_cpf": "1231234345543",
    "ie_rg": "123456",
    "endereco": null,
    "numero": null,
    "cep": null,
    "telefone": null,
    "celular": null
}
####MUDAR NEGOCIOS
POST http://localhost:8000/api/business/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2OTA5OTk3ODMsImV4cCI6MTY5MTAwMzM4MywibmJmIjoxNjkwOTk5NzgzLCJqdGkiOiJWQ1IwNjI5YUp6VGo2Rk9YIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Nxbg24G_I6fUWhM6V3Sr14UNpiX2mSoEeFc2GzVLnt8
Content-Type: application/json
Accept: application/json

{
    "_method": "PUT",
    "fantasia": "TNET SISTEMASs",
    "razao": " TNET LTDA",
    "cnpj_cpf": "1231234345543",
    "ie_rg": "123456",
    "endereco": null,
    "numero": null,
    "cep": null,
    "telefone": null,
    "celular": null
}
####APAGAR NEGOCIOS
POST http://localhost:8000/api/business/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2OTA5OTk3ODMsImV4cCI6MTY5MTAwMzM4MywibmJmIjoxNjkwOTk5NzgzLCJqdGkiOiJWQ1IwNjI5YUp6VGo2Rk9YIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Nxbg24G_I6fUWhM6V3Sr14UNpiX2mSoEeFc2GzVLnt8
Content-Type: application/json
Accept: application/json

{
    "_method": "DELETE"
}
